# This is a config for E2B sandbox template.
# You can use template ID (1i0x5sdfs7btx88e8jzp) or template name (vibe-next-js-test-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-js-test-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-js-test-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-js-test-3')

team_id = "d8d759e7-c949-4521-a69e-c76bbd55ef7d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-js-test-3"
template_id = "1i0x5sdfs7btx88e8jzp"
